### ISSUE TITLE
Build error with now 17.0.3

### ISSUE THREAD

**Issue by cbfn** [frontity/now-builder#21]
## Problem

Now cli 17.0.3 show the following error message while deploying using npm run build && now --prod

```
TypeError: Cannot read property 'fsPath' of undefined
2020-02-07T12:33:50.534Z      at Object.build (/zeit/b027f802d99b8095/.build-utils/.builder/node_modules/@frontity/now/dist/index.js:95:49)
2020-02-07T12:33:50.534Z      at async buildStep (/var/task/sandbox-worker.js:20292:20)
2020-02-07T12:33:50.534Z      at async mainSub (/var/task/sandbox-worker.js:20047:9)
2020-02-07T12:33:50.534Z      at async main (/var/task/sandbox-worker.js:19975:5)
```

**Comment by luisherranz** [comment]
I'm not able to reproduce the problem with a clean repo.

Could you please provide a minimal repo example of this error?

Please start with a clean `npx frontity create` and this `now.json` file:
``` json
{
  "version": 2,
  "builds": [
    {
      "src": "package.json",
      "use": "@frontity/now"
    }
  ]
}
``` 
and only add the necessary changes to make it break.

**Comment by cbfn** [comment]
It works well. The problem I think is related with gitlab-ci so my build directory is removed in gitlab-ci starts deployment. I think that I need to remove the build directory from .gitignore

**Comment by cbfn** [comment]
Everything works well. Thanks!

**Comment by luisherranz** [comment]
Awesome! Thanks @cbfn. If you have more problems in the future feel free to open another issue :)
