### ISSUE TITLE
Error: The legacy "@frontity/now" Builder is not supported.

### ISSUE THREAD

**Issue by IlyaSemenov** [frontity/now-builder#35]
OK, this package is apparently officially outdated.

Today my build failed with Error: The legacy "@frontity/now" Builder is not supported.

```
[13:55:44.807] Retrieving list of deployment files...
[13:55:46.669] Downloading 131 deployment files...
[13:55:50.959] Looking up build cache...
[13:55:51.091] Build Cache not found
[13:55:51.430] Warning: Due to "engines": { "node": ">=10.0.0" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
[13:55:51.433] Running "vercel build"
[13:55:52.005] Vercel CLI 24.2.5-canary.0 build (beta) — https://vercel.com/feedback
[13:55:52.130] ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
[13:55:52.130] │ WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings │
[13:55:52.131] └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
[13:55:52.560] yarn add v1.22.17
[13:55:52.596] info No lockfile found.
[13:55:52.626] [1/4] Resolving packages...
[13:55:53.460] warning @frontity/now > @now/node-bridge@1.3.1: "@now/node-bridge" is deprecated and will stop receiving updates January 2021. Please use "@vercel/node-bridge" instead.
[13:55:53.462] [2/4] Fetching packages...
[13:55:53.631] [3/4] Linking dependencies...
[13:55:53.632] warning " > @frontity/now@1.2.0" has unmet peer dependency "@now/build-utils@^0.9.4".
[13:55:53.710] [4/4] Building fresh packages...
[13:55:53.715] success Saved lockfile.
[13:55:53.723] success Saved 3 new dependencies.
[13:55:53.723] info Direct dependencies
[13:55:53.724] ├─ @frontity/now@1.2.0
[13:55:53.725] └─ @vercel/build-utils@3.1.0
[13:55:53.725] info All dependencies
[13:55:53.725] ├─ @frontity/now@1.2.0
[13:55:53.726] ├─ @now/node-bridge@1.3.1
[13:55:53.726] └─ @vercel/build-utils@3.1.0
[13:55:53.729] Done in 1.18s.
[13:55:54.283] Error! An unexpected error occurred in build: Error: The legacy "@frontity/now" Builder is not supported.
[13:55:54.283]     at Object.importBuilders (/var/task/node_modules/vercel/dist/index.js:233012:31)
[13:55:54.283]     at main (/var/task/node_modules/vercel/dist/index.js:225537:30)
[13:55:54.283]     at main (/var/task/node_modules/vercel/dist/index.js:232427:20)
[13:55:54.297] Error: Command "vercel build" exited with 1
```

**Comment by IlyaSemenov** [comment]
@swarnava Can you shed any light on this please? https://vercel.com/changelog doesn't mention anything on this truly breaking change.

**Comment by swarnava** [comment]
This package hasn't been updated for a long time. 

> [13:55:53.460] warning @frontity/now > @now/node-bridge@1.3.1: "@now/node-bridge" is deprecated and will stop receiving updates January 2021. Please use "@vercel/node-bridge" instead.

I am not even sure it's being actively maintained. Maybe someone from Frontify team can take a look.

This looks scary:

```
[13:55:51.430] Warning: Due to "engines": { "node": ">=10.0.0" } in your `package.json` file, the Node.js Version defined in your Project Settings ("14.x") will not apply. Learn More: http://vercel.link/node-version
```

This builder hasn't been updated since July 2020. I suggest you can send a PR to `vercel/vercel` repo use zero config instead of a custom builder

**Comment by luisherranz** [comment]
Closing in favor of https://github.com/frontity/now-builder/issues/34.
